src/crud/urls.py
from django.urls import path
from .views import formularyAddUpdate, index, formularyAddUpdate, addEmployee, updateEmployee, deleteEmployee, downloadCSVFile


app_name = 'crud'
urlpatterns = [
    path('', index),
    path('formulary/<str:method>/<int:id>/', formularyAddUpdate, name="formulary"),
    path('add/', addEmployee, name="add-e"),
    path('update/<int:id>/', updateEmployee, name="update-e"),
    path('delete/<int:id>/', deleteEmployee, name="delete-e"),
    path('download/csv/', downloadCSVFile, name="download-csv"),
]

src/employee_management/urls.py
from django.shortcuts import redirect
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('crud/', include('crud.urls')),
    path('', lambda request: redirect('crud/')),
]

src/crud/models.py
from django.db import models


# Create your models here.


class Employee(models.Model):
    first_name = models.CharField(max_length=30, verbose_name="Firstname")
    last_name = models.CharField(max_length=30, verbose_name="Lastname")
    email = models.EmailField(verbose_name="Email")
    phone = models.CharField(max_length=13, verbose_name="Phone number")
    location = models.CharField(max_length=50, verbose_name="Location")
    university = models.CharField(max_length=50, verbose_name="University")

    def __str__(self):
        return f"{self.first_name} {self.last_name} | {self.phone}"

src/crud/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

import csv

from .models import Employee
# Create your views here.


def index(request):
    alldata = Employee.objects.all()
    return render(request, "index.html", {"alldata": alldata})


def formularyAddUpdate(request, method: str, id=""):
    if method == "update":
        target = Employee.objects.get(id=id)
        return render(request, "add-update-formulary.html", {"method": method, "id": id, "target": target})

    return render(request, "add-update-formulary.html", {"method": method, "id": id})


def addEmployee(request):
    new_data = [request.POST.get("firstname"),
                request.POST.get("lastname"),
                request.POST.get("email"),
                request.POST.get("phone"),
                request.POST.get("location"),
                request.POST.get("university")]

    if None in new_data:
        return HttpResponse("Data not inserted, there was a shortage.")

    Employee.objects.create(first_name=new_data[0],
                            last_name=new_data[1],
                            email=new_data[2],
                            phone=new_data[3],
                            location=new_data[4],
                            university=new_data[5])

    return redirect("/crud/")


def updateEmployee(request, id):
    target = Employee.objects.get(id=id)
    new_data = [request.POST.get("firstname"),
                request.POST.get("lastname"),
                request.POST.get("email"),
                request.POST.get("phone"),
                request.POST.get("location"),
                request.POST.get("university")]

    if None in new_data:
        return HttpResponse("New data not inserted, there was a shortage.")

    target.first_name = new_data[0]
    target.last_name = new_data[1]
    target.email = new_data[2]
    target.phone = new_data[3]
    target.location = new_data[4]
    target.university = new_data[5]

    target.save()

    return redirect("/crud/")


def deleteEmployee(request, id):
    employee = Employee.objects.get(id=id)
    employee.delete()

    return redirect("/crud/")


def downloadCSVFile(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="database-data.csv"'

    writer = csv.writer(response)
    writer.writerow(['Firstname', 'lastname', 'email',
                    'phone', 'location', 'university'])

    employees_data = Employee.objects.all()
    for employee in employees_data:
        writer.writerow([employee.first_name,
                         employee.last_name,
                         employee.email,
                         employee.phone,
                         employee.location,
                         employee.university])

    return response

src/crud/templates/add-update-formulary.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/add-update-formulary/styles.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300&family=Mochiy+Pop+One&family=Red+Hat+Mono&family=Roboto:wght@300&family=Source+Sans+Pro:ital@1&family=Ubuntu:wght@300&display=swap" rel="stylesheet">
    <title>Formulary</title>
</head>
<body>
    {% if method == 'add' %}
        <h1>CRUD DATABASE</h1>
        <h3>Add employee</h3>
        <form action="{% url 'crud:add-e'%}" method="post">{% csrf_token %}
            <div class="formulary-items-flex">
                <label for="firstname">Firstname</label>
                <input type="text" id="firstname" name="firstname" placeholder="Insert here">
                <label for="lastname">Lastname</label>
                <input type="text" id="lastname" name="lastname" placeholder="Insert here">
                <label for="email">Email</label>
                <input type="text" id="email" name="email" placeholder="Insert here">
                <label for="phone">Phone</label>
                <input type="text" id="phone" name="phone" placeholder="Insert here">
                <label for="location">Location</label>
                <input type="text" id="location" name="location" placeholder="Insert here">
                <label for="university">University</label>
                <input type="text" id="university" name="university" placeholder="Insert here">
    
                <input type="submit" value="Save">
            </div>
        </form>
    {% else %}
        <h1>CRUD DATABASE</h1>
        <h3>Update employee</h3>
        <form action="{% url 'crud:update-e' id=id%}" method="post">{% csrf_token %}
            <div class="formulary-items-flex">
                <label for="firstname">Firstname</label>
                <input type="text" id="firstname" name="firstname" value="{{ target.first_name }}"  placeholder="Insert here">
                <label for="lastname">Lastname</label>
                <input type="text" id="lastname" name="lastname" value="{{ target.last_name }}" placeholder="Insert here">
                <label for="email">Email</label>
                <input type="text" id="email" name="email" value="{{ target.email }}" placeholder="Insert here">
                <label for="phone">Phone</label>
                <input type="text" id="phone" name="phone" value="{{ target.phone }}" placeholder="Insert here">
                <label for="location">Location</label>
                <input type="text" id="location" name="location" value="{{ target.location }}" placeholder="Insert here">
                <label for="university">University</label>
                <input type="text" id="university" name="university" value="{{ target.university }}" placeholder="Insert here">
    
                <input type="submit" value="Save">
            </div>
        </form>
    {% endif %}
    <div class="footer">
        <footer>
            <h4>
                Made by: Luis Quiñones Requelme | 14/11/2021
            </h4>
        </footer>
    </div>
</body>
</html>

src/crud/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/index/styles.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300&family=Mochiy+Pop+One&family=Red+Hat+Mono&family=Roboto:wght@300&family=Source+Sans+Pro:ital@1&family=Ubuntu:wght@300&display=swap" rel="stylesheet">
    <title>CRUD Database</title>
</head>
<body>
    <h1>CRUD Database</h1>
    <div class="table">
        <div id="download-add-flex">
            <a id="download-csv" href="{% url 'crud:download-csv' %}">Download CSV</a>    
            <a id="add-item" href="{% url 'crud:formulary' method='add' id=0 %}">Add Item</a>
        </div>
        <table>
            <tr>
                <th>ID</th>
                <th>Firstname</th>
                <th>Lastname</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Location</th>
                <th>University</th>
                <th>Action one</th>
                <th>Action two</th>
            </tr>
            {% for data in alldata %}
            <tr class="row-data">
                <td>{{ data.id }}</td>
                <td>{{ data.first_name }}</td>
                <td>{{ data.last_name }}</td>
                <td>{{ data.email }}</td>
                <td>{{ data.phone }}</td>
                <td>{{ data.location }}</td>
                <td>{{ data.university }}</td>
                <td><a href="{% url 'crud:formulary' method='update' id=data.id %}" class="update">Update</a></td>
                <td><a href="{% url 'crud:delete-e' id=data.id %}" class="delete">Delete</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
    <div class="footer">
        <footer>
            <h4>
                Made by: Luis Quiñones Requelme | 14/11/2021
            </h4>
        </footer>
    </div>
</body>
</html>